# Generated by Django 5.1.2 on 2024-10-23 20:20

import django.utils.timezone
# Generated by Django 5.1.2 on 2024-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_name", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
