# Generated by Django 5.1.2 on 2024-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tripitem_alter_usermodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
    ]
